# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.10
_src_path: https://github.com/jupyterlab/extension-template
author_email: fcollonval@gmail.com
author_name: Frederic Collonval
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: server
labextension_name: jupyterlab-rise
mimetype: ''
mimetype_name: ''
project_short_description: 'RISE: "Live" Reveal.js JupyterLab Slideshow extension.'
python_name: jupyterlab_rise
repository: https://github.com/jupyterlab-contrib/rise
test: true
viewer_name: ''

