# a mybinder.org-ready environment for demoing jupyterlab_rise
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-rise-demo
#
name: jupyterlab-rise-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - jupyterlab >=4,<5.0.0a0
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  # additional packages for demos
  - ipywidgets
  - matplotlib-base
  - numpy
