name: Check Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Install Dependencies
        run: |
          # Install dependencies for bump_version script
          python -m pip install hatch "jupyterlab~=3.1"
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:

          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distributions
        uses: actions/upload-artifact@v2
        with:
          name: jupyterlab_rise-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist